-- AlterTable
ALTER TABLE "Job" ADD COLUMN     "dateCreated" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "dateApplied" DROP NOT NULL,
ALTER COLUMN "dateApplied" DROP DEFAULT,
ALTER COLUMN "dateApplied" SET DATA TYPE TEXT;
